--
-- Table for the recipes
--
CREATE TABLE `recipe` (
  `id` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `instructions` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `recipe`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `recipe`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- Table for the ingredients
--
CREATE TABLE `ingredient` (
  `id` int(11) NOT NULL,
  `recipe_id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `quantity` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ingredient`
  ADD PRIMARY KEY (`id`),
  ADD KEY `recipe_fk` (`recipe_id`);

ALTER TABLE `ingredient`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- Foreign key
--
ALTER TABLE `ingredient`
  ADD CONSTRAINT `recipe_fk` FOREIGN KEY (`recipe_id`) REFERENCES `recipe` (`id`);














--
-- Insert the recipes
-- The recipes id is automatically generated by MySQL
--
INSERT INTO `recipe`
  (`title`,
   `instructions`)
VALUES
  ('Boiling Water',
   'Put the water in a cauldron and boil.'),
  ('Tea',
   'Prepare the recipe for boiling water. Put the water in a cup, add the tea bag and let it steep for a few minutes.'),
  ('Glass of water',
   'Put ice cubes in a tall glass and fill with water. Add a slice of lemon if desired.');

--
-- Insert the ingredients for each recipe
-- The ingredient id is automatically generated by MySQL
-- but we select the id of the corresponding recipe by searching by its title
--
INSERT INTO `ingredient`
  (`recipe_id`,
   `name`,
   `quantity`)
VALUES
  ((SELECT `id` FROM `recipe` WHERE `title` = 'Boiling Water'),
   'Fresh water',
   '250 ml'),
  ((SELECT `id` FROM `recipe` WHERE `title` = 'Tea'),
   'Fresh water',
   '250 ml'),
  ((SELECT `id` FROM `recipe` WHERE `title` = 'Tea'),
   'Tea bag',
   '1'),
  ((SELECT `id` FROM `recipe` WHERE `title` = 'Glass of water'),
   'Fresh water',
   '300 ml'),
  ((SELECT `id` FROM `recipe` WHERE `title` = 'Glass of water'),
   'Ice cubes',
   '2-3'),
  ((SELECT `id` FROM `recipe` WHERE `title` = 'Glass of water'),
   'Lemon (optional)',
   '1 slice');